# frozen_string_literal: true

#
# DO NOT EDIT THIS FILE MANUALLY
#
class Localbeach < Formula
  desc "Command-line tool for Flownative Beach"
  homepage "https://www.flownative.com/beach"
  license "GPL-3.0-or-later"
  version "v1.3.2+1"

  if RUBY_PLATFORM.downcase.include?("darwin")
    url "https://github.com/flownative/localbeach/releases/download/v1.3.2+1/beach_darwin_amd64.zip"
    sha256 "a4ebb820ca31043ba070d5326a9740ac50cf07fe654a07b85dc5d7645039aa9f"
  else
    url "https://github.com/flownative/localbeach/releases/download/v1.3.2+1/beach_linux_amd64.zip"
    sha256 "7a1f6cf6b7a1ac527c6630b8b11e92d2545fc629682a39dc5325fcbfd8cb7e73"
  end

  bottle :unneeded

  conflicts_with "flownative/flownative/beach-cli", because: "localbeach replaces beach-cli"

  depends_on "mkcert" => :run
  depends_on "nss" => :run

  def install
    database_path = RUBY_PLATFORM.downcase.include?("darwin") ? "~/Library/Application Support/Flownative/Local Beach/MariaDB" : "~/.Flownative/Local Beach/MariaDB"

    bin.install "beach" => "beach"
    system "#{bin}/beach", "setup", "--docker-folder", "#{lib}/localbeach", "--database-folder", database_path
  end

  def caveats
  <<~EOS
Local Beach is built on top of Docker and Docker Compose. You will need a working setup of both in order to use Local
Beach.
  EOS
  end
end
