# frozen_string_literal: true

#
# DO NOT EDIT THIS FILE MANUALLY
#
class Localbeach < Formula
  desc "Command-line tool for Flownative Beach"
  homepage "https://www.flownative.com/localbeach"
  version "1.18.0+2"
  license "GPL-3.0-or-later"

  on_macos do
    on_intel do
      url "https://github.com/flownative/localbeach/releases/download/1.18.0+2/beach_darwin_amd64.zip"
      sha256 ""
    end
    on_arm do
      url "https://github.com/flownative/localbeach/releases/download/1.18.0+2/beach_darwin_arm64.zip"
      sha256 ""
    end
  end

  on_linux do
    url "https://github.com/flownative/localbeach/releases/download/1.18.0+2/beach_linux_amd64.zip"
    sha256 "5d8adc1b6e20929821ce004a655ea10317896b7722aed2dd419ce9c0e3dd2b8c"
  end

  depends_on "mkcert"
  depends_on "nss"

  def install
    bin.install "beach" => "beach"
  end

  def caveats
    <<~EOS
    Local Beach is built on top of Docker and Docker Compose.
    You will need a working setup of both in order to use Local Beach.
    EOS
  end
end
