# frozen_string_literal: true

#
# DO NOT EDIT THIS FILE MANUALLY
# It is written by the release workflow of flownative/minka-cli.
#
class Minka < Formula
  desc "Command-line client for Minka, built for people and for AI agents"
  homepage "https://github.com/flownative/minka-cli"
  url "git@github.com:flownative/minka-cli.git",
      using:    :git,
      tag:      "v0.6.0",
      revision: "12f452deb6cf48f58ea76bcf2e35a19e9e295b13"
  version "0.6.0"
  license :cannot_represent

  depends_on "go" => :build

  def install
    ldflags = "-s -w -X github.com/flownative/minka-cli/internal/cli.version=#{version}"
    system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/minka"
    generate_completions_from_executable(bin/"minka", "completion")
  end

  def caveats
    <<~EOS
      First steps, on a terminal:
        minka setup

      After an upgrade, bring the skill for agents up to date:
        minka skill install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/minka version --styled")
  end
end
